site_name: 读书笔记
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

pages:
    - 简介: 'index.md'
    - 职场:
      - 《give and take》: 'career/give_and_take.md'
    - 代码:
      - 《代码大全》: 'code/代码大全.md'
    - 数据库:
      - 《mysql必知必会》: 'database/mysql必知必会.md'
    - 前端:
      - 《CSS_The_Missing_Manual》: 'frontend/CSS_The_Missing_Manual.md'
    - golang:
      - 《The Go Programming Language》: 'golang/1_the_go_programming_lauguage.md'
    - 心理学:
      - 《一切都是童年的错吗》: 'psychology/一切都是童年的错吗.md'
    - python:
      - 《Fluent Python》: 'python/fluent_python.md'
      - 《Python Microservices Development》: 'python/Python_Microservices_Development.md'
    - 创业:
      - 《Hello Startup》: 'startup/hello_startup.md'
    - unix/linux:
      - 《Linux高性能服务器编程》: 'unix_linux/Linux高性能服务器编程.md'
    - 分布式:
      - 《分布式框架原理与应用》:  '分布式/分布式框架原理与应用.md'
    - 开发工具:
      - 《Practical Vim》: '开发工具/practical_vim/practical_vim.md'
      - 《Learn vim scrpt the hard way》: '开发工具/learn_vim_the_hard_way.md'
      - 《Pro Git》: '开发工具/pro_git.md'
    - 思维:
      - 《高效程序员的45个习惯》: '思维/高效程序员的45个习惯.md'
    - 源码:
      - 《源码阅读》: '源码阅读_sourcecode/README.md'
    - 网站架构:
      - 《web scalavility for startup engineers》: '网站架构/web_scalavility_for_startup_engineers.md'
    - 软件工程/项目管理:
      - 《构建之法:现代软件工程》: '软件工程_项目管理/构建之法:现代软件工程.md'
    - 运维:
      - 《python自动化运维》: '运维/python自动化运维.md'
    - 金融理财:
      - 《穷查理宝典》: '金融_finance/穷查理宝典.md'
    - 区块链:
      - 《区块链技术指南》: '区块链/区块链技术指南(blockchain_guide).md'
